apiVersion: 1

policies:
  - orgId: 1
    receiver: incident-response
    group_by: ["alertname"]
    routes:
      - receiver: incident-response
        object_matchers:
          - ["severity", "=", "critical"]
